services:
  api:
    build: .
    container_name: hirebridge-pro-api
    ports: ["3000:3000"]
    env_file: [.env]
    depends_on: [mongo]
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]
volumes:
  mongo_data:
